"""initial migration

Revision ID: 299fd53a3ab6
Revises: 
Create Date: 2026-05-09 10:12:32.026579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299fd53a3ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_hns', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seller_hns_address', sa.String(length=100), nullable=False),
    sa.Column('gfavip_user_id', sa.String(length=100), nullable=True),
    sa.Column('gfavip_username', sa.String(length=100), nullable=True),
    sa.Column('ipfs_cid', sa.String(length=100), nullable=False),
    sa.Column('proof_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_name'))

    op.drop_table('listings')
    # ### end Alembic commands ###
